name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Debug before running build.sh
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents before build.sh:"
          ls -la

      - name: creates output
        run: sh ./build.sh

      - name: Debug after running build.sh
        run: |
          echo "Directory contents after build.sh:"
          ls -la
          echo "Output directory contents:"
          ls -la output

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v1
        env:
          API_TOKEN_GITHUB: ${{ secrets.SEN_GITHUB_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: marchfirst01
          destination-repository-name: dice-host-deploy
          user-email: ${{ secrets.SEN_ACCOUNT_EMAIL }}

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
